# Build Stage
FROM node:23-alpine AS build

# Install required build tools
RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json . 
COPY .env /app/.env

# Clean install
RUN rm -rf node_modules package-lock.json && npm install

COPY . .

CMD [ "npm", "run", "dev" ]