SecRuleEngine DetectionOnly

SecRequestBodyAccess On
SecResponseBodyAccess Off

SecRequestBodyLimit 41943040
SecRequestBodyNoFilesLimit 1048576

SecAuditEngine RelevantOnly
SecAuditLog /dev/stdout

Include /etc/modsecurity.d/owasp-crs/crs-setup.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf