# Generated by Django 5.2.6 on 2026-04-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_fr', models.TextField(blank=True, null=True)),
                ('question_es', models.TextField(blank=True, null=True)),
                ('question_zh', models.TextField(blank=True, null=True)),
                ('question_ru', models.TextField(blank=True, null=True)),
                ('answer_fr', models.TextField(blank=True, null=True)),
                ('answer_es', models.TextField(blank=True, null=True)),
                ('answer_zh', models.TextField(blank=True, null=True)),
                ('answer_ru', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_wards/')),
                ('features', models.JSONField(blank=True, default=list)),
                ('name_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('name_es', models.CharField(blank=True, max_length=150, null=True)),
                ('name_zh', models.CharField(blank=True, max_length=150, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('title_es', models.CharField(blank=True, max_length=100, null=True)),
                ('title_zh', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('tagline', models.CharField(max_length=255)),
                ('tagline_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline_es', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline_zh', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField()),
                ('overview_fr', models.TextField(blank=True, null=True)),
                ('overview_es', models.TextField(blank=True, null=True)),
                ('overview_zh', models.TextField(blank=True, null=True)),
                ('overview_ru', models.TextField(blank=True, null=True)),
                ('detailedDescription', models.TextField(blank=True, null=True)),
                ('detailedDescription_fr', models.TextField(blank=True, null=True)),
                ('detailedDescription_es', models.TextField(blank=True, null=True)),
                ('detailedDescription_zh', models.TextField(blank=True, null=True)),
                ('detailedDescription_ru', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('isBookable', models.BooleanField(default=False)),
                ('hasReadMore', models.BooleanField(default=False)),
                ('ftOnHomepage', models.BooleanField(default=False)),
                ('clinics', models.ManyToManyField(blank=True, related_name='parent_services', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalServiceFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='clinical_services/features/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinical_services/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('focal_x', models.FloatField(default=50.0)),
                ('focal_y', models.FloatField(default=20.0)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('role', models.CharField(max_length=100)),
                ('role_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('role_es', models.CharField(blank=True, max_length=100, null=True)),
                ('role_zh', models.CharField(blank=True, max_length=100, null=True)),
                ('role_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('bio_fr', models.TextField(blank=True, null=True)),
                ('bio_es', models.TextField(blank=True, null=True)),
                ('bio_zh', models.TextField(blank=True, null=True)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('research_publications', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('services_offered', models.ManyToManyField(blank=True, related_name='offered_by_doctors', to='clinics.clinicalservice')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='clinics.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='OutpatientCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('timings', models.JSONField(blank=True, default=list)),
                ('services_offered', models.ManyToManyField(blank=True, related_name='outpatient_centers', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='OutpatientCenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outpatient_centers/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('outpatient_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.outpatientcenter')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='clinics.testimonial'),
        ),
    ]
