# Generated by Django 5.2.6 on 2026-01-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('detailedDescription', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('isBookable', models.BooleanField(default=False)),
                ('hasReadMore', models.BooleanField(default=False)),
                ('clinics', models.ManyToManyField(blank=True, related_name='parent_services', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalServiceFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='clinical_services/features/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinical_services/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.clinicalservice')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('research_publications', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('services_offered', models.ManyToManyField(blank=True, related_name='offered_by_doctors', to='clinics.clinicalservice')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='clinics.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='OutpatientCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('timings', models.JSONField(blank=True, default=list)),
                ('services_offered', models.ManyToManyField(blank=True, related_name='outpatient_centers', to='clinics.clinicalservice')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='clinics.testimonial'),
        ),
    ]
