# Generated by Django 5.2.6 on 2025-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='related_services',
        ),
        migrations.RenameField(
            model_name='clinicalservice',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clinicalservice',
            name='is_bookable',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='detailedDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='hasReadMore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='isBookable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RelatedService',
        ),
    ]
