# Generated by Django 5.2.6 on 2026-02-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='detailedDescription_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='detailedDescription_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='detailedDescription_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='detailedDescription_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='overview_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='overview_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='overview_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='overview_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='tagline_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='tagline_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='tagline_zh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role_zh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outpatientcenter',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpatientcenter',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpatientcenter',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpatientcenter',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
