# Generated by Django 5.2.6 on 2026-02-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_doctor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_fr', models.TextField(blank=True, null=True)),
                ('question_es', models.TextField(blank=True, null=True)),
                ('question_zh', models.TextField(blank=True, null=True)),
                ('question_ru', models.TextField(blank=True, null=True)),
                ('answer_fr', models.TextField(blank=True, null=True)),
                ('answer_es', models.TextField(blank=True, null=True)),
                ('answer_zh', models.TextField(blank=True, null=True)),
                ('answer_ru', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
