# Generated by Django 5.2.6 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinicalfaq"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomWard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, null=True, upload_to="room_wards/")),
                ("name_fr", models.CharField(blank=True, max_length=150, null=True)),
                ("name_es", models.CharField(blank=True, max_length=150, null=True)),
                ("name_zh", models.CharField(blank=True, max_length=150, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
