# Generated by Django 5.2.6 on 2026-02-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_roomward"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomward",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
