# Generated by Django 5.2.6 on 2025-12-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_delete_contact_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
