# Generated by Django 5.2.6 on 2025-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='title',
            new_name='role',
        ),
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='research_publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_offered',
            field=models.ManyToManyField(blank=True, related_name='offered_by_doctors', to='clinics.clinicalservice'),
        ),
    ]
