# Generated by Django 5.2.6 on 2026-02-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_roomward'),
        ('clinics', '0005_alter_clinicalservice_path'),
    ]

    operations = [
    ]
