# Generated by Django 5.2.6 on 2025-12-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_rename_title_doctor_role_doctor_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalservice',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='clinics.doctor'),
        ),
    ]
