# Generated by Django 5.2.6 on 2026-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinicalservice_ft_on_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='path',
        ),
    ]
