# Generated by Django 5.2.6 on 2026-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_remove_clinicalservice_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalservice',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
