# Generated by Django 5.2.6 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0010_merge_0008_outpatientcenterimage_0009_clinicalservice_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalserviceimage",
            name="focal_x",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="clinicalserviceimage",
            name="focal_y",
            field=models.FloatField(default=20.0),
        ),
    ]
