# Generated by Django 5.2.6 on 2025-12-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinical_services/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.clinicalservice')),
            ],
        ),
    ]
