# Generated by Django 5.2.6 on 2025-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_clinicalserviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalserviceimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
