# Generated by Django 5.2.6 on 2026-01-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_alter_clinicalserviceimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='DoctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='clinics.doctor')),
            ],
        ),
    ]
