# Generated by Django 5.2.6 on 2026-01-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_alter_doctor_image_doctorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='images',
        ),
    ]
