# Generated by Django 5.2.6 on 2026-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_remove_clinicalservice_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('timings', models.JSONField(blank=True, null=True)),
                ('services_offered', models.ManyToManyField(blank=True, related_name='outpatient_centers', to='clinics.clinicalservice')),
            ],
        ),
    ]
