# Generated by Django 5.2.6 on 2026-01-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_outpatientcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatientcenter',
            name='timings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
