# Generated by Django 5.2.6 on 2026-01-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_outpatientcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalServiceFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='clinical_services/features/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='clinics.clinicalservice')),
            ],
        ),
    ]
