export interface Blog {
  id?: string;
  title: string;
  subtitle?: string;
  subtitle_fr?: string;
  subtitle_es?: string;
  subtitle_zh?: string;
  subtitle_ru?: string;
  author: string;
  category?: string;
  category_fr?: string;
  category_es?: string;
  category_zh?: string;
  category_ru?: string;
  shortdesc?: string;
  shortdesc_fr?: string;
  shortdesc_es?: string;
  shortdesc_zh?: string;
  shortdesc_ru?: string;
  longdesc?: string;
  longdesc_fr?: string;
  longdesc_es?: string;
  longdesc_zh?: string;
  longdesc_ru?: string;
  cover_image?: string;
  image?: string;
  isFeatured?: boolean;
  group: "ARTICLES" | "EVENTS" | "NEWS";
  type: "article" | "event" | "news";
}
