export interface CSR {
  id: number | string;
  author: string;
  title: string;
  subtitle?: string;
  blogsubtitle?: string;
  blog_subtitle?: string;
  description?: string;
  description_fr?: string;
  description_es?: string;
  description_zh?: string;
  description_ru?: string;
  shortdesc?: string;
  short_desc?: string;
  shortdesc_fr?: string;
  short_desc_fr?: string;
  shortdesc_es?: string;
  short_desc_es?: string;
  shortdesc_zh?: string;
  short_desc_zh?: string;
  shortdesc_ru?: string;
  short_desc_ru?: string;
  longdesc?: string;
  long_desc?: string;
  longdesc_fr?: string;
  long_desc_fr?: string;
  longdesc_es?: string;
  long_desc_es?: string;
  longdesc_zh?: string;
  long_desc_zh?: string;
  longdesc_ru?: string;
  long_desc_ru?: string;
  coverImage?: string;
  cover_image?: string;
  cover_image_alt?: string;
  image?: string[];
}
