### GET /

GET http://localhost:5003


### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Log in a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Fetch all Clinical Services GET /CLINICAL-SERVICES
GET http://localhost:5003/clinical-services
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MjEwNTk0LCJleHAiOjE3NTYyOTY5OTR9.txa0k4o4iVQUda1Os3qzF7rIfec4PLrwIYSqIcjG2c0


### Create a Clinical Service POST /CLINICAL-SERVICES
POST http://localhost:5003/clinical-services
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MjEwNTk0LCJleHAiOjE3NTYyOTY5OTR9.txa0k4o4iVQUda1Os3qzF7rIfec4PLrwIYSqIcjG2c0

{
    "title": "General Checkup",
    "tagline": "Comprehensive health assessment",
    "overview": "A thorough examination to evaluate overall health.",
    "features":  "Physical examination, Vital signs measurement, Health history review",
        
    "testimonial": "Excellent service and care!",
    "contact":"123-456-7890",
    "clinics":"Downtown Clinic, Uptown Clinic",
    "related_services":"Blood Test, X-Ray",
    "image_url": "http://example.com/image.jpg",
    "image_alt": "General Checkup Image"
}

### Update a Clinical Service PATCH /CLINICAL-SERVICES/:id
PATCH http://localhost:5003/clinical-services/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MjEwNTk0LCJleHAiOjE3NTYyOTY5OTR9.txa0k4o4iVQUda1Os3qzF7rIfec4PLrwIYSqIcjG2c0

{
  
    "overview": "a"
  
}

### Delete a Clinical Service DELETE /CLINICAL-SERVICES/:id
DELETE http://localhost:5003/clinical-services/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MjEwNTk0LCJleHAiOjE3NTYyOTY5OTR9.txa0k4o4iVQUda1Os3qzF7rIfec4PLrwIYSqIcjG2c0  


  