# Generated by Django 5.2.6 on 2026-01-13 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('blogsubtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('shortdesc', models.TextField()),
                ('longdesc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('coverImage', models.URLField(max_length=500)),
                ('image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
