# Generated by Django 5.2.6 on 2025-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='title',
            new_name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
