# Generated by Django 5.2.6 on 2026-01-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
    ]
