# Generated by Django 5.2.6 on 2026-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_subtitle_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_subtitle_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_subtitle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_subtitle_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='long_desc_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='long_desc_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='long_desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='long_desc_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_desc_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_desc_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_desc_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='blog_subtitle_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='blog_subtitle_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='blog_subtitle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='blog_subtitle_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='description_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='long_desc_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='long_desc_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='long_desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='long_desc_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='short_desc_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='short_desc_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='short_desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='short_desc_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='subtitle_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='title_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='csr',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='group_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='group_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='group_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='group_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
