# Generated by Django 5.2.6 on 2026-02-05 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0002_blogpost_blog_subtitle_es_blogpost_blog_subtitle_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opportunity_type', models.CharField(default='Tender', max_length=50)),
                ('date_posted', models.DateField()),
                ('closing_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='tenders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
