# Generated by Django 5.2.6 on 2025-12-22 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0003_alter_teammember_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('blog_subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('cover_image', models.URLField()),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
