# Generated by Django 5.2.6 on 2026-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0003_alter_blogpost_blogsubtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
