# Generated by Django 5.2.6 on 2026-02-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0003_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_fr', models.CharField(blank=True, max_length=255)),
                ('location_es', models.CharField(blank=True, max_length=255)),
                ('location_zh', models.CharField(blank=True, max_length=255)),
                ('location_ru', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_zh', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('requirements', models.TextField()),
                ('requirements_fr', models.TextField(blank=True)),
                ('requirements_es', models.TextField(blank=True)),
                ('requirements_zh', models.TextField(blank=True)),
                ('requirements_ru', models.TextField(blank=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
