# Generated by Django 5.2.6 on 2026-01-15 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0004_alter_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('blogsubtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('shortdesc', models.TextField()),
                ('longdesc', models.TextField()),
                ('coverImage', models.URLField(blank=True, max_length=500)),
                ('image', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
