# Generated by Django 5.2.6 on 2026-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0005_csr'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/'),
        ),
    ]
