# Generated by Django 5.2.6 on 2026-02-13 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0006_career_dates_and_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_zh', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_section/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
