# Generated by Django 5.2.6 on 2026-02-15 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generalinfo", "0007_hero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                ("doctor", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("patient_name", models.CharField(max_length=255)),
                ("patient_phone", models.CharField(max_length=50)),
                ("patient_email", models.EmailField(max_length=254)),
                ("additional_info", models.TextField(blank=True)),
                ("slot_key", models.CharField(editable=False, max_length=512, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
