# Generated by Django 5.2.6 on 2026-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0007_blogpost_coverimage_alt_blogpost_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csr',
            name='coverImage',
        ),
        migrations.RemoveField(
            model_name='csr',
            name='image',
        ),
        migrations.AddField(
            model_name='csr',
            name='cover_image',
            field=models.ImageField(blank=True, db_column='cover_image', null=True, upload_to='csr/covers/'),
        ),
        migrations.AddField(
            model_name='csr',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
