# Generated by Django 5.2.6 on 2026-01-26 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0008_remove_csr_coverimage_remove_csr_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogsubtitle',
            new_name='blog_subtitle',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='coverImage',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='coverImage_alt',
            new_name='cover_image_alt',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='isFeatured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='longdesc',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='shortdesc',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='csr',
            old_name='blogsubtitle',
            new_name='blog_subtitle',
        ),
        migrations.RenameField(
            model_name='csr',
            old_name='longdesc',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='csr',
            old_name='shortdesc',
            new_name='short_desc',
        ),
        migrations.AlterField(
            model_name='csr',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='csr/covers/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
